AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Plantilla YAML para crear una instancia EC2 para el Frontend (FE2).

Parameters:
  NombreInstanciaFront:
    Description: Nombre de la instancia frontend FE2
    Type: String
    MinLength: 5
  AMI:
    Description: ID de la imagen de la instancia
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/jammy/stable/current/amd64/hvm/ebs-gp2/ami-id
  TipoInstancia:
    Description: Tipo de instancia permitida
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.nano
      - t2.large
  KeyName:
    Description: Nombre de la llave para la instancia
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey
  Identificador:
    Description: Identificador para la instancia Frontend FE2
    Type: String
    Default: SoyFront2

Resources:
  InstanciaFrontend:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: !Ref NombreInstanciaFront
      ImageId: !Ref AMI
      InstanceType: !Ref TipoInstancia
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - Fn::ImportValue: GrupoSeguridadSSH
        - Fn::ImportValue: GrupoSeguridadHTTP
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash -xe
            exec > /tmp/userdata.log 2>&1
            apt update -y
            apt install python3-pip -y
            pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
            ln -s /usr/local/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
            sudo sed -i 's/^\$nrconf{restart} = "i";/\$nrconf{restart} = "a";/' /etc/needrestart/needrestart.conf
            sudo sed -i 's/^\$nrconf{kernelhints} = -1;/\$nrconf{kernelhints} = -1;/' /etc/needrestart/needrestart.conf
            sudo sed -i 's/^\$nrconf{checks} = 1;/\$nrconf{checks} = 0;/' /etc/needrestart/needrestart.conf
            apt update -y
            apt install apache2 git -y
            a2enmod proxy
            a2enmod proxy_http
            a2enmod proxy_balancer
            a2enmod lbmethod_byrequests
            echo "<VirtualHost *:80>
            ServerName ajimsan2009.ejemplo.com
            ServerAlias *
            DocumentRoot /var/www/html
            ProxyPass "/api/" "http://${IPPublica}:8080/studentify/api/"
            ProxyPassReverse "/api/" "http://${IPPublica}:8080/studentify/api/"
            <Proxy "balancer://cluster">
                BalancerMember "http://${IPPublica}:8080"
            </Proxy>
            </VirtualHost>" > /etc/apache2/sites-available/frontend.conf
            mkdir -p /var/www/html
            mkdir -p /tmp/frontend_repo
            git clone https://github.com/DavidHormigoRamirez/frontend_daw.git /tmp/frontend_repo
            cp -r /tmp/frontend_repo/* /var/www/html/
            # Insertar el identificador en la primera línea del index.html:
            sed -i "1i <h1>${Identificador}</h1>" /var/www/html/index.html
            sudo chmod -R 777 /var/www/html
            sudo chown -R www-data:www-data /var/www/html
            sed -i "s/CAMBIAR/\/api\/students/g" /var/www/html/index.html
            sed -i "s/fetch('CAMBIAR',/fetch('\/api\/students',/g" /var/www/html/create.html
            a2dissite 000-default.conf
            a2ensite frontend.conf
            systemctl restart apache2
            /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource InstanciaFrontend --region ${AWS::Region}
          - { IPPublica: !ImportValue IPPublica }

Outputs:
  IPFrontendPrivada:
    Description: IP privada de la instancia Frontend FE2
    Value: !GetAtt InstanciaFrontend.PrivateIp
    Export:
      Name: FE2PrivateIP
  IPFrontendPublica:
    Description: IP publica de la instancia Frontend FE2
    Value: !GetAtt InstanciaFrontend.PublicIp
    Export:
      Name: FE2PublicIP
